from abc import ABC, abstractmethod
from typing import Optional
from app.core.domain.entities.judge import JudgeOutput


class JudgeService(ABC):
    """Port for judge LLM service that evaluates factual correctness"""

    @abstractmethod
    async def evaluate_answer(
        self,
        question: str,
        retrieved_context: str,
        llm_answer: str,
        ground_truth: Optional[str] = None
    ) -> JudgeOutput:
        """
        Evaluate the factual correctness of an LLM answer based on retrieved context.

        Args:
            question: The original user question
            retrieved_context: The context retrieved from the document store
            llm_answer: The answer generated by the LLM
            ground_truth: Optional ground truth answer for comparison

        Returns:
            JudgeOutput with correctness evaluation, reasoning, and identified issues
        """
        pass
